# Generated by Django 5.1.4 on 2024-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
