# Generated by Django 5.1.4 on 2024-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0002_customuser_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fastapi_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
